"""Self-contained HTML report.

One file you can open in a browser, attach to a paper, or drop into an
MDR / FDA evaluation dossier. No external assets, no network.
"""

from __future__ import annotations

import math
from typing import TYPE_CHECKING

from jinja2 import Template

from segauge.core import METRIC_DIRECTION
from segauge.types import Estimate

if TYPE_CHECKING:
    from segauge.core import EvaluationResult


def _fmt(value: float) -> str:
    if value is None or (isinstance(value, float) and math.isnan(value)):
        return "n/a"
    if math.isinf(value):
        return "&#8734;" if value > 0 else "-&#8734;"
    return f"{value:.4g}"


def _fmt_est(est: Estimate) -> dict[str, str]:
    return {
        "value": _fmt(est.value),
        "ci": f"[{_fmt(est.ci_low)}, {_fmt(est.ci_high)}]",
    }


_TEMPLATE = Template(
    """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{{ title }}</title>
<style>
  :root { color-scheme: light dark; }
  body { font: 15px/1.5 -apple-system, system-ui, sans-serif; margin: 2rem auto;
         max-width: 60rem; padding: 0 1rem; }
  h1 { font-size: 1.5rem; margin-bottom: .25rem; }
  .sub { color: #777; margin-top: 0; }
  table { border-collapse: collapse; width: 100%; margin: 1rem 0 2rem; }
  th, td { text-align: left; padding: .4rem .6rem; border-bottom: 1px solid #ddd; }
  th { font-weight: 600; }
  td.num, th.num { text-align: right; font-variant-numeric: tabular-nums; }
  .ci { color: #888; font-size: .9em; }
  .dir { color: #aaa; font-size: .85em; }
  caption { text-align: left; font-weight: 600; margin: .5rem 0; }
  footer { color: #999; font-size: .85em; margin-top: 3rem; }
</style>
</head>
<body>
<h1>{{ title }}</h1>
<p class="sub">{{ n_cases }} case(s) &middot; {{ confidence }}% bootstrap CI
   ({{ n_resamples }} resamples, seed {{ seed }})</p>

<table>
  <caption>Summary</caption>
  <thead><tr><th>Metric</th><th class="num">Value</th>
    <th class="num">{{ confidence }}% CI</th><th>Better</th></tr></thead>
  <tbody>
  {% for m in summary %}
    <tr><td>{{ m.name }}</td>
        <td class="num">{{ m.value | safe }}</td>
        <td class="num ci">{{ m.ci | safe }}</td>
        <td class="dir">{{ m.direction }}</td></tr>
  {% endfor %}
  </tbody>
</table>

{% for group in subgroups %}
<table>
  <caption>By {{ group.key }}</caption>
  <thead><tr><th>{{ group.key }}</th>
    {% for name in metric_names %}
      <th class="num">{{ name }}</th>
    {% endfor %}</tr></thead>
  <tbody>
  {% for value in group.entries %}
    <tr><td>{{ value.label }} <span class="ci">(n={{ value.n }})</span></td>
      {% for cell in value.cells %}
        <td class="num">{{ cell | safe }}</td>
      {% endfor %}</tr>
  {% endfor %}
  </tbody>
</table>
{% endfor %}

<table>
  <caption>Per case</caption>
  <thead><tr><th>case</th>
    {% for name in metric_names %}
      <th class="num">{{ name }}</th>
    {% endfor %}</tr></thead>
  <tbody>
  {% for row in per_case %}
    <tr><td>{{ row.case_id }}</td>
      {% for cell in row.cells %}
        <td class="num">{{ cell | safe }}</td>
      {% endfor %}</tr>
  {% endfor %}
  </tbody>
</table>

<footer>Generated by segauge &middot; geometrically-correct, DICOM-native
  segmentation evaluation.</footer>
</body>
</html>
"""
)


def render_html(
    result: EvaluationResult, title: str = "segauge evaluation report"
) -> str:
    summary = [
        {"name": name, "direction": METRIC_DIRECTION.get(name, ""), **_fmt_est(est)}
        for name, est in result.summary().items()
    ]

    subgroups = []
    for key in result.metadata_keys:
        entries = []
        for label, metrics in result.by_subgroup(key).items():
            n = sum(1 for r in result.rows if r.get(f"meta.{key}") == label)
            entries.append(
                {
                    "label": str(label),
                    "n": n,
                    "cells": [_fmt(metrics[m].value) for m in result.metric_names],
                }
            )
        subgroups.append({"key": key, "entries": entries})

    per_case = [
        {
            "case_id": row.get("case_id", "?"),
            "cells": [
                _fmt(float(row[m])) if m in row else "n/a" for m in result.metric_names
            ],
        }
        for row in result.rows
    ]

    return _TEMPLATE.render(
        title=title,
        n_cases=len(result.rows),
        confidence=round(result.confidence * 100),
        n_resamples=result.n_resamples,
        seed=result.seed,
        metric_names=result.metric_names,
        summary=summary,
        subgroups=subgroups,
        per_case=per_case,
    )
